# Generated by Django 5.2.10 on 2026-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internlink', '0003_remove_profile_company_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
