# Generated by Django 5.2.10 on 2026-02-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internlink', '0005_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='portfolio_url',
        ),
    ]
